# Generated by Django 5.0.1 on 2024-02-13 06:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("NovaBazaar", "0002_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="ProductName",
            new_name="Product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="Price",
        ),
    ]
