# Generated by Django 5.0.2 on 2024-02-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NovaBazaar", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(upload_to="media/products/"),
        ),
    ]
