# Generated by Django 5.0.1 on 2024-02-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NovaBazaar", "0003_rename_productname_product_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="Category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="Order",
        ),
        migrations.RemoveField(
            model_name="product",
            name="Product",
        ),
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
