# Generated by Django 5.0.2 on 2024-02-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NovaBazaar", "0004_remove_cart_product_remove_cart_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="discription",
            field=models.TextField(),
        ),
    ]
