# Generated by Django 5.0.2 on 2024-02-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NovaBazaar", "0005_alter_cart_discription"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="product_image",
            field=models.ImageField(default=1, upload_to="Product/"),
            preserve_default=False,
        ),
    ]
