# Generated by Django 5.0.2 on 2024-02-26 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("NovaBazaar", "0006_cart_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="price",
            new_name="selling_price",
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="discription",
        ),
    ]
