# Generated by Django 5.0.2 on 2024-02-26 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NovaBazaar", "0007_rename_price_cart_selling_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="product_image",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="selling_price",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="title",
        ),
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="NovaBazaar.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
