# Generated by Django 5.0.2 on 2024-02-29 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NovaBazaar", "0010_remove_order_quantity_remove_order_total_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="NovaBazaar.customer",
            ),
            preserve_default=False,
        ),
    ]
