# Generated by Django 5.0.2 on 2024-02-29 06:52

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "NovaBazaar",
            "0012_rename_city_order_phone_remove_order_name_order_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="date",
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True
            ),
        ),
    ]
