# Generated by Django 5.0.2 on 2024-02-29 07:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NovaBazaar", "0013_remove_order_date_alter_order_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date",
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
